### ISSUE TITLE
Styling to control the grid, line thickness, label size, etc

### ISSUE THREAD

**Issue by heman-theman** [mauriciopoppe/function-plot#234]
Hello 
Thanks for this plotter, it's great.

I want to be able to change the settings on the grid, line thickness, size of labels, etc..  Your docs page is down. Do you have another location for the documentation?

Thanks

**Comment by minoush82** [comment]
Yes, there is a pressing need for this.

I see you are  ahead of me, you seem to want to control the size of the labels. I cannot figure out how to put a label in the first place. Care to share your wisdom?

**Comment by mauriciopoppe** [comment]
With CSS:

```css
.function-plot .y.axis text {
  font-size: 30px;
}
```

You could do similar overrides through CSS for other components.

**Comment by heman-theman** [comment]
And for the thickness of the graph?  Thanks

**Comment by mauriciopoppe** [comment]
The following only works with the `graphType: 'polyline'` graphtype

```css
.function-plot path.line {
  stroke-width: 5;
}
```
