### ISSUE TITLE
legend text chopped off when drawn wide

### ISSUE THREAD

**Issue by timelyportfolio** [mauriciopoppe/function-plot#67]
I absolutely love `function-plot` and appreciate all the work you have done.

As shown in the screenshot below from this [CodePen reproducible example](http://codepen.io/timelyportfolio/pen/GqpQbV), the legend text gets chopped off when a function is plotted wide.

![image](https://cloud.githubusercontent.com/assets/837910/15873961/96903d16-2cc6-11e6-8ad1-380524a8e1f1.png)

The text `y` is set on this [line](https://github.com/maurizzzio/function-plot/blob/b5c5c8ab6c97daf71ad38056f810e70b3ca7ac97/lib/index.js#L229) `.attr('y', margin.top / 2)`.  Could we also additionally set the attr `dy = "0.5em"`?

Alternately, could we set `margins` in `options`?  Occasionally, other text, such as the axis, gets chopped off in the same context.

Thanks!!

**Comment by maurizzzio** [comment]
Thanks for the feedback, since this is a style only issue I think it'd be better to override the style on an external stylesheet

```css
/* change the default font-size */
.function-plot {
  font-size: 10px;
}
/* or change only the font size of the legend */
.function-plot .top-right-legend {
  font-size: 10px;
}
```

In any case I agree that the default font-size given to the graph may be wrong, I will try to address this in a further release
